baseURL = "https://night0721.xyz/"
title = "Oscar Fu"

[permalinks]
    post = "/blog/:slug"

[menu]
    [[menu.main]]
        name = "About"
        url = "/about"
        weight = 10

    [[menu.main]]
        name = "Projects"
        url = "/#projects"
        weight = 20

    [[menu.main]]
        name = "Posts"
        url = "/posts"
        weight = 30

    [[menu.main]]
        name = "Contact"
        url = "/contact"
        weight = 40

    [[menu.main]]
        name = "Links"
        url = "/links"
        weight = 50

    [[menu.main]]
        name = "Donate"
        url = "https://ko-fi.com/cathteam"
        weight = 60
    
    [[menu.social]]
        name = "Discord"
        pre = "discord"
        url = "https://discord.gg/SbQHChmGcp"
        weight = 10

    [[menu.social]]
        name = "GitHub"
        pre = "github"
        url = "https://github.com/night0721"
        weight = 20

    [[menu.social]]
        name = "YouTube"
        pre = "youtube"
        url = "https://youtube.com/@night0721"
        weight = 30

    [[menu.social]]
        name = "RSS Feed"
        pre = "rss"
        url = "/index.xml"
        weight = 40



[markup]
  [markup.goldmark.parser]
    wrapStandAloneImageWithinParagraph = false
  [markup.highlight]
    style = 'catppuccin-macchiato'
